version: "3"
services:
  python_app:
    build:
      context: .
      dockerfile: ./Dockerfile_selenium
    depends_on:
      - redis
    networks:
      mi_red:
        ipv4_address: 172.20.0.2

  python_app_2:
    build:
      context: .
      dockerfile: ./Dockerfile_play
    depends_on:
      - redis
    networks:
      mi_red:
        ipv4_address: 172.20.0.3
  
   
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      mi_red:
        ipv4_address: 172.20.0.5

networks:
  mi_red:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16